name: data_emulator_workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Change to data-emulator directory
        run: cd data-emulator
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: |
          cd data-emulator
          npm install
          npm run lint
      #- run: npm test