name: battery_emulator_workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: data-emulator # Set the directory to data-emulator
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm --prefix data-emulator run lint # Run npm commands in the data-emulator directory
      # - run: npm --prefix data-emulator test # Run npm commands in the data-emulator directory