name: data-emulator-workflow

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name:  npm install, lint
        run: |
          cd data-emulator
          npm install
          npm run lint

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name:  npm install, test
        run: |
          cd data-emulator
          npm install
          npm run test