name: data-emulator-workflow

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name:  npm install, lint
        run: |
          cd data-emulator
          npm install
          npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name:  npm install, test
        run: |
          cd data-emulator
          npm install
          npm run test

  docker_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd data-emulator
          docker build -t ${{ secrets.DOCKER_USERNAME }}/data-emulator:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/data-emulator:latest